// <auto-generated />
namespace BanDoGiaDung.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ThemBangLucDau_DaSuaLoi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThemBangLucDau_DaSuaLoi));
        
        string IMigrationMetadata.Id
        {
            get { return "202511111031295_ThemBangLucDau_DaSuaLoi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
